analyze_channel: 13.0
aperiodic_mode: knee
aperiodic_mode_tuning_max_n_peaks: fixed
aperiodic_mode_tuning_peak_threshold: fixed
channels_to_load: 13-16,24
condition_groupings:
  '1':
    label: All Conditions
    conditions:
    - AdriveVlast
    - AknownVmeant
    - AlastVknown
    - AmeantVdrive
    - drive_a
    - drive_av
    - drive_v
    - known_a
    - known_av
    - known_v
    - last_a
    - last_av
    - last_v
    - meant_a
    - meant_av
    - meant_v
    - press_AV
  '2':
    label: Visual
    conditions:
    - last_v
    - drive_v
    - known_v
    - meant_v
  '3':
    label: Audio
    conditions:
    - last_a
    - drive_a
    - known_a
    - meant_a
epoch_name: auditory_onset
freq_range:
- 1
- 200
freq_range_aperiodic_tuning:
- 1
- 200
freq_range_tuning_max_n_peaks:
- 1
- 200
freq_range_tuning_peak_threshold:
- 1
- 200
individual_trials: no
max_n_peaks: 7
max_n_peaks_aperiodic_tuning: 7
max_n_peaks_tuning_peak_threshold: 7
number_of_threshold_value_tuning_peak_threshold: 50
peaks_range_tuning_max_n_peaks:
- 1
- 2
- 3
plt_log: no
project_name: demo
reference_name: default
standard_deviation: 1
subject_code: DemoSubject
threshold_value_range_tuning_peak_threshold:
- 1
- 5
time_window_to_load:
- -1
- 2
window_length: 1
