analyze_channel: 15.0
channels_to_load: 13-16,24
condition_groupings:
  '1':
    label: All Conditions
    conditions:
    - AdriveVlast
    - AknownVmeant
    - AlastVknown
    - AmeantVdrive
    - drive_a
    - drive_av
    - drive_v
    - known_a
    - known_av
    - known_v
    - last_a
    - last_av
    - last_v
    - meant_a
    - meant_av
    - meant_v
    - press_AV
epoch_name: auditory_onset
freq_range:
- 1.0
- 200.0
individual_trials: no
project_name: demo
reference_name: default
subject_code: DemoSubject
time_window_to_load:
- -1
- 2
window_length: 1
