analyze_channel: 13.0
aperiodic_mode: fixed
channels_to_load: 13-16,24
condition_groupings:
  '1':
    label: All Conditions
    conditions:
    - AdriveVlast
    - AknownVmeant
    - AlastVknown
    - AmeantVdrive
    - drive_a
    - drive_av
    - drive_v
    - known_a
    - known_av
    - known_v
    - last_a
    - last_av
    - last_v
    - meant_a
    - meant_av
    - meant_v
    - press_AV
  '2':
    label: www
    conditions:
    - AknownVmeant
    - known_a
    - meant_v
  '3':
    label: wwwwwwww
    conditions:
    - meant_a
    - known_av
    - AmeantVdrive
epoch_name: auditory_onset
freq_range:
- 1.0
- 56.6
freq_range_aperiodic_tuning:
- 1
- 300
individual_trials: no
max_n_peaks: 3
max_n_peaks_aperiodic_tuning: 15
plt_log: no
project_name: demo
reference_name: default
subject_code: DemoSubject
time_window_to_load:
- -1
- 2
window_length: 1
