analyze_channel: 13.0
aperiodic_mode: fixed
aperiodic_mode_tuning_max_n_peaks: knee
aperiodic_mode_tuning_peak_threshold: knee
channels_to_load: 13-16,24
condition_groupings:
  '1':
    label: All Conditions
    conditions:
    - AdriveVlast
    - AknownVmeant
    - AlastVknown
    - AmeantVdrive
    - drive_a
    - drive_av
    - drive_v
    - known_a
    - known_av
    - known_v
    - last_a
    - last_av
    - last_v
    - meant_a
    - meant_av
    - meant_v
    - press_AV
  '2':
    label: Testing
    conditions:
    - AdriveVlast
  '3':
    label: Testing Again
    conditions:
    - drive_a
epoch_name: auditory_onset
freq_range:
- 1.0
- 50.1
freq_range_aperiodic_tuning:
- 1
- 300
freq_range_tuning_max_n_peaks:
- 1
- 300
freq_range_tuning_peak_threshold:
- 1
- 300
individual_trials: no
max_n_peaks: 11
max_n_peaks_aperiodic_tuning: 5
max_n_peaks_tuning_peak_threshold: 5
number_of_threshold_value_tuning_peak_threshold: 100
peaks_range_tuning_max_n_peaks:
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
- 13
- 14
- 15
plt_log: no
project_name: demo
reference_name: default
subject_code: DemoSubject
threshold_value_range_tuning_peak_threshold:
- 1
- 10
time_window_to_load:
- -1
- 2
window_length: 1
