analyze_channel: 13.0
aperiodic_mode: knee
channels_to_load: 13-16,24
condition_groupings:
  '1':
    label: All Conditions
    conditions:
    - AdriveVlast
    - AknownVmeant
    - AlastVknown
    - AmeantVdrive
    - drive_a
    - drive_av
    - drive_v
    - known_a
    - known_av
    - known_v
    - last_a
    - last_av
    - last_v
    - meant_a
    - meant_av
    - meant_v
    - press_AV
  '2':
    label: a
    conditions:
    - drive_a
    - known_a
    - last_a
    - meant_a
  '3':
    label: v
    conditions:
    - drive_v
    - last_v
    - known_v
    - meant_v
epoch_name: auditory_onset
freq_range:
- 1.0
- 300.0
freq_range_aperiodic_tuning:
- 1.0
- 300.0
individual_trials: no
max_n_peaks: 5
max_n_peaks_aperiodic_tuning: 5
plt_log: no
project_name: demo
reference_name: default
subject_code: DemoSubject
time_window_to_load:
- -1
- 2
window_length: 1
