controllers:
  Background Color: '#FFFFFF'
data_source: Uploads
data_source_pipeline: power_explorer/power_explorer-22_09_03-22_54_46
data_source_pipeline_target: omnibus_results
data_source_project: demo
main_camera:
  target:
    x: 0.1824112
    'y': 5.4496269
    z: 29.8170767
  position:
  - -464.7486621
  - 63.3923834
  - -9.975475
  up:
  - -0.0066071
  - 0.4619897
  - 0.8868607
  zoom: 1.0
project_name: demo
shiny_outputId: custom_3d_viewer-viewer_ready
subject_code: DemoSubject
surface_types: ~
uploaded_source: electrode_value(3).fst
use_template: no
