baseline:
- - -1
  - -0.2
baseline_method: decibel
controllers: []
electrodes: 14-16
epoch: auditory_onset
intervals:
- - -1.0
  - 2.0
main_camera: []
path_to_connectivity_matrix: /var/folders/7s/395jkmts5j91y3sgjjgvh5kc0000gn/T//Rtmpan0kzA/9b208b50ab3141da55d8726b/0.csv
path_to_electrodes: /var/folders/7s/395jkmts5j91y3sgjjgvh5kc0000gn/T//Rtmpan0kzA/d3bebd23387e2bec60896163/0.csv
project_name: ~
reference: default
save_pipeline: yes
selected_template: cvs_avg35_inMNI152
shiny_outputId: connectivity_viewer-viewer_ready
subject_code: ~
surface_types:
- white
- smoothwm
type: power
uploaded_source: ~
use_template: ~
