electrode_export_data_type: tensor
electrodes_to_export: ''
trials_to_export: Raw, Only trials used in grouping factors
times_to_export: Raw, All available times
frequencies_to_export: Collapsed, Analysis window(s) only
electrode_export_file_type: HDF5
trial_outliers_list: ~
time_censor:
  enabled: no
  window:
  - 0.0
  - 1.0
project_name: demo
subject_code: DemoSubject
loaded_electrodes: 13-16,24
epoch_choice: auditory_onset
epoch_choice__trial_starts: -1
epoch_choice__trial_ends: 2
reference_name: default
baseline_settings:
  window:
  - - -1.0
    - -0.5
  scope: Per frequency, trial, and electrode
  unit_of_analysis: '% Change Power'
analysis_electrodes: '14'
first_condition_groupings:
  '1':
    label: audio_visual
    conditions:
    - known_av
    - meant_av
    - last_av
    - drive_av
  '2':
    label: auditory_only
    conditions:
    - last_a
    - drive_a
    - known_a
    - meant_a
  '3':
    label: visual_only
    conditions:
    - last_v
    - drive_v
    - known_v
    - meant_v
second_condition_groupings:
  '1':
    label: ML
    conditions: []
  '2':
    label: VL
    conditions: []
enable_second_condition_groupings: no
condition_variable: Condition
enable_custom_ROI: no
custom_roi_type: Filter only
custom_roi_variable: none
custom_roi_groupings:
  '1':
    label: ''
    conditions: []
analysis_settings:
  '1':
    label: VisStart
    event: Trial Onset
    time:
    - 0
    - 1
    frequency:
    - 70
    - 150
omnibus_includes_all_electrodes: no
electrodes_to_export_roi_name: none
electrodes_to_export_roi_categories: ~
epoch_choice__trial_ends_rel_to_event: Trial Onset
epoch_choice__trial_starts_rel_to_event: Trial Onset
